### ISSUE TITLE
adding quantity in card is not correct

### ISSUE THREAD

**Issue by SOURABHs23** [cn10xdev/ECommerce_Product_Page#29]
we have to add +1 if its not there, its adding all quantity directly

**Comment by Ezio-Sarthak** [comment]
Can you provide more context for this? Why was this opened and then closed as completed?

**Comment by SOURABHs23** [comment]
const addToCart = (product) => {
        let updatedCart = [...cart];
        const productIndex = updatedCart.findIndex(item => item.id === product.id);
        if (productIndex !== -1) {
            updatedCart[productIndex].quantity += 1;
        } else {
            updatedCart.push(product);
        }
        setCart(updatedCart);
    };
    
    Sir, in provided code, if adding new product in cart it directly pushes whole object in cart, this is wrong lets suppose if that product have 10 quantity it directly pushed all 10 in card, we have to do like that
    updatedCart.push({ ...product, quantity: 1 }); we have add 1 not all
